version: "3"
services:
  
  rest:
    build: .

# FUSE inside Docker: https://stackoverflow.com/questions/48402218/fuse-inside-docker
    devices:
      - "/dev/fuse:/dev/fuse"
#    privileged: true
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    volumes:
      - /root/.local/share/wize/fs
    container_name: wizefs-node
    ports:
      - "13000:13000"