// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wizefs_service.proto

/*
Package wizefsservice is a generated protocol buffer package.

It is generated from these files:
	wizefs_service.proto

It has these top-level messages:
	FilesystemRequest
	FilesystemResponse
	PutRequest
	PutResponse
	GetRequest
	GetResponse
*/
package wizefsservice

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FilesystemRequest struct {
	Origin string `protobuf:"bytes,1,opt,name=origin" json:"origin,omitempty"`
}

func (m *FilesystemRequest) Reset()                    { *m = FilesystemRequest{} }
func (m *FilesystemRequest) String() string            { return proto.CompactTextString(m) }
func (*FilesystemRequest) ProtoMessage()               {}
func (*FilesystemRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *FilesystemRequest) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

type FilesystemResponse struct {
	Executed bool   `protobuf:"varint,1,opt,name=executed" json:"executed,omitempty"`
	Message  string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *FilesystemResponse) Reset()                    { *m = FilesystemResponse{} }
func (m *FilesystemResponse) String() string            { return proto.CompactTextString(m) }
func (*FilesystemResponse) ProtoMessage()               {}
func (*FilesystemResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *FilesystemResponse) GetExecuted() bool {
	if m != nil {
		return m.Executed
	}
	return false
}

func (m *FilesystemResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type PutRequest struct {
	Filename string `protobuf:"bytes,1,opt,name=filename" json:"filename,omitempty"`
	Content  []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Origin   string `protobuf:"bytes,3,opt,name=origin" json:"origin,omitempty"`
}

func (m *PutRequest) Reset()                    { *m = PutRequest{} }
func (m *PutRequest) String() string            { return proto.CompactTextString(m) }
func (*PutRequest) ProtoMessage()               {}
func (*PutRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PutRequest) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *PutRequest) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *PutRequest) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

type PutResponse struct {
	Executed bool   `protobuf:"varint,1,opt,name=executed" json:"executed,omitempty"`
	Message  string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *PutResponse) Reset()                    { *m = PutResponse{} }
func (m *PutResponse) String() string            { return proto.CompactTextString(m) }
func (*PutResponse) ProtoMessage()               {}
func (*PutResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PutResponse) GetExecuted() bool {
	if m != nil {
		return m.Executed
	}
	return false
}

func (m *PutResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetRequest struct {
	Filename string `protobuf:"bytes,1,opt,name=filename" json:"filename,omitempty"`
	Origin   string `protobuf:"bytes,2,opt,name=origin" json:"origin,omitempty"`
}

func (m *GetRequest) Reset()                    { *m = GetRequest{} }
func (m *GetRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()               {}
func (*GetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GetRequest) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *GetRequest) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

type GetResponse struct {
	Executed bool   `protobuf:"varint,1,opt,name=executed" json:"executed,omitempty"`
	Message  string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	Content  []byte `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
}

func (m *GetResponse) Reset()                    { *m = GetResponse{} }
func (m *GetResponse) String() string            { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()               {}
func (*GetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GetResponse) GetExecuted() bool {
	if m != nil {
		return m.Executed
	}
	return false
}

func (m *GetResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetResponse) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func init() {
	proto.RegisterType((*FilesystemRequest)(nil), "wizefsservice.FilesystemRequest")
	proto.RegisterType((*FilesystemResponse)(nil), "wizefsservice.FilesystemResponse")
	proto.RegisterType((*PutRequest)(nil), "wizefsservice.PutRequest")
	proto.RegisterType((*PutResponse)(nil), "wizefsservice.PutResponse")
	proto.RegisterType((*GetRequest)(nil), "wizefsservice.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "wizefsservice.GetResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for WizeFsService service

type WizeFsServiceClient interface {
	Create(ctx context.Context, in *FilesystemRequest, opts ...grpc.CallOption) (*FilesystemResponse, error)
	Delete(ctx context.Context, in *FilesystemRequest, opts ...grpc.CallOption) (*FilesystemResponse, error)
	Mount(ctx context.Context, in *FilesystemRequest, opts ...grpc.CallOption) (*FilesystemResponse, error)
	Unmount(ctx context.Context, in *FilesystemRequest, opts ...grpc.CallOption) (*FilesystemResponse, error)
	// potential client-side streaming RPC:
	// client sends a sequence of messages using a provided stream
	// server read them and return its response
	Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error)
	// potential server-side streaming RPC:
	// client sends a request and gets a stream to read a sequence of messages
	// server sends a sequence of messages
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
}

type wizeFsServiceClient struct {
	cc *grpc.ClientConn
}

func NewWizeFsServiceClient(cc *grpc.ClientConn) WizeFsServiceClient {
	return &wizeFsServiceClient{cc}
}

func (c *wizeFsServiceClient) Create(ctx context.Context, in *FilesystemRequest, opts ...grpc.CallOption) (*FilesystemResponse, error) {
	out := new(FilesystemResponse)
	err := grpc.Invoke(ctx, "/wizefsservice.WizeFsService/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wizeFsServiceClient) Delete(ctx context.Context, in *FilesystemRequest, opts ...grpc.CallOption) (*FilesystemResponse, error) {
	out := new(FilesystemResponse)
	err := grpc.Invoke(ctx, "/wizefsservice.WizeFsService/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wizeFsServiceClient) Mount(ctx context.Context, in *FilesystemRequest, opts ...grpc.CallOption) (*FilesystemResponse, error) {
	out := new(FilesystemResponse)
	err := grpc.Invoke(ctx, "/wizefsservice.WizeFsService/Mount", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wizeFsServiceClient) Unmount(ctx context.Context, in *FilesystemRequest, opts ...grpc.CallOption) (*FilesystemResponse, error) {
	out := new(FilesystemResponse)
	err := grpc.Invoke(ctx, "/wizefsservice.WizeFsService/Unmount", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wizeFsServiceClient) Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error) {
	out := new(PutResponse)
	err := grpc.Invoke(ctx, "/wizefsservice.WizeFsService/Put", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wizeFsServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := grpc.Invoke(ctx, "/wizefsservice.WizeFsService/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for WizeFsService service

type WizeFsServiceServer interface {
	Create(context.Context, *FilesystemRequest) (*FilesystemResponse, error)
	Delete(context.Context, *FilesystemRequest) (*FilesystemResponse, error)
	Mount(context.Context, *FilesystemRequest) (*FilesystemResponse, error)
	Unmount(context.Context, *FilesystemRequest) (*FilesystemResponse, error)
	// potential client-side streaming RPC:
	// client sends a sequence of messages using a provided stream
	// server read them and return its response
	Put(context.Context, *PutRequest) (*PutResponse, error)
	// potential server-side streaming RPC:
	// client sends a request and gets a stream to read a sequence of messages
	// server sends a sequence of messages
	Get(context.Context, *GetRequest) (*GetResponse, error)
}

func RegisterWizeFsServiceServer(s *grpc.Server, srv WizeFsServiceServer) {
	s.RegisterService(&_WizeFsService_serviceDesc, srv)
}

func _WizeFsService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilesystemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WizeFsServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wizefsservice.WizeFsService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WizeFsServiceServer).Create(ctx, req.(*FilesystemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WizeFsService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilesystemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WizeFsServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wizefsservice.WizeFsService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WizeFsServiceServer).Delete(ctx, req.(*FilesystemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WizeFsService_Mount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilesystemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WizeFsServiceServer).Mount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wizefsservice.WizeFsService/Mount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WizeFsServiceServer).Mount(ctx, req.(*FilesystemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WizeFsService_Unmount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilesystemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WizeFsServiceServer).Unmount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wizefsservice.WizeFsService/Unmount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WizeFsServiceServer).Unmount(ctx, req.(*FilesystemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WizeFsService_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WizeFsServiceServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wizefsservice.WizeFsService/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WizeFsServiceServer).Put(ctx, req.(*PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WizeFsService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WizeFsServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wizefsservice.WizeFsService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WizeFsServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WizeFsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "wizefsservice.WizeFsService",
	HandlerType: (*WizeFsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _WizeFsService_Create_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _WizeFsService_Delete_Handler,
		},
		{
			MethodName: "Mount",
			Handler:    _WizeFsService_Mount_Handler,
		},
		{
			MethodName: "Unmount",
			Handler:    _WizeFsService_Unmount_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _WizeFsService_Put_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _WizeFsService_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wizefs_service.proto",
}

func init() { proto.RegisterFile("wizefs_service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 316 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x86, 0xdb, 0x06, 0xdb, 0x3a, 0xb5, 0x07, 0x17, 0x91, 0x9a, 0x53, 0xcd, 0x49, 0x10, 0x7a,
	0xd0, 0xbb, 0x08, 0x95, 0x16, 0x04, 0xb5, 0x44, 0x44, 0x10, 0x44, 0x6a, 0x7c, 0x5b, 0x16, 0x92,
	0xdd, 0x9a, 0xdd, 0xf8, 0xd1, 0xbf, 0xe9, 0x1f, 0x92, 0x6e, 0x92, 0x26, 0x31, 0x22, 0x42, 0x73,
	0x7c, 0x37, 0x33, 0xcf, 0x3e, 0xcb, 0x4c, 0x68, 0xef, 0x9d, 0x2f, 0x31, 0x53, 0x4f, 0x0a, 0xe1,
	0x1b, 0xf7, 0x30, 0x58, 0x84, 0x52, 0x4b, 0xd6, 0x8d, 0x4f, 0x93, 0x43, 0xe7, 0x98, 0x76, 0x47,
	0xdc, 0x87, 0xfa, 0x54, 0x1a, 0x81, 0x8b, 0xd7, 0x08, 0x4a, 0xb3, 0x7d, 0x6a, 0xca, 0x90, 0xcf,
	0xb9, 0xe8, 0xd5, 0xfb, 0xf5, 0xa3, 0x6d, 0x37, 0x49, 0xce, 0x25, 0xb1, 0x7c, 0xb1, 0x5a, 0x48,
	0xa1, 0xc0, 0x6c, 0x6a, 0xe3, 0x03, 0x5e, 0xa4, 0xf1, 0x62, 0xea, 0xdb, 0xee, 0x3a, 0xb3, 0x1e,
	0xb5, 0x02, 0x28, 0x35, 0x9d, 0xa3, 0xd7, 0x30, 0xa8, 0x34, 0x3a, 0x0f, 0x44, 0x93, 0x48, 0xa7,
	0x37, 0xda, 0xd4, 0x9e, 0x71, 0x1f, 0x62, 0x1a, 0x20, 0xb9, 0x73, 0x9d, 0x57, 0x0c, 0x4f, 0x0a,
	0x0d, 0xa1, 0x0d, 0x63, 0xc7, 0x4d, 0x63, 0xce, 0xd3, 0x2a, 0x78, 0x0e, 0xa9, 0x63, 0xd8, 0x1b,
	0x09, 0x9e, 0x13, 0x8d, 0xf1, 0x2f, 0xc1, 0x4c, 0xa3, 0x51, 0xd0, 0x78, 0xa4, 0x8e, 0x21, 0x6c,
	0xa2, 0x91, 0x7f, 0xbd, 0x55, 0x78, 0xfd, 0xc9, 0x97, 0x45, 0xdd, 0x7b, 0xbe, 0xc4, 0x48, 0xdd,
	0xc6, 0xc3, 0x64, 0x37, 0xd4, 0x1c, 0x86, 0x98, 0x6a, 0xb0, 0xfe, 0xa0, 0x30, 0xe6, 0x41, 0x69,
	0xc6, 0xf6, 0xe1, 0x1f, 0x15, 0xb1, 0xb0, 0x53, 0x5b, 0x01, 0x2f, 0xe0, 0xa3, 0x3a, 0xe0, 0x35,
	0x6d, 0x5d, 0xc9, 0x48, 0xe8, 0xaa, 0x78, 0x13, 0x6a, 0xdd, 0x89, 0xa0, 0x4a, 0xe2, 0x19, 0x59,
	0x93, 0x48, 0xb3, 0x83, 0x1f, 0xb5, 0xd9, 0xae, 0xda, 0xf6, 0x6f, 0x9f, 0xf2, 0xfd, 0x63, 0x94,
	0xfb, 0xb3, 0x55, 0x2a, 0xf5, 0xe7, 0x76, 0xc4, 0xa9, 0x3d, 0x37, 0xcd, 0x6f, 0x7a, 0xfa, 0x1d,
	0x00, 0x00, 0xff, 0xff, 0x64, 0x17, 0x83, 0x36, 0xbe, 0x03, 0x00, 0x00,
}
